### ISSUE TITLE
Extra code and tutorial?

### ISSUE THREAD

**Issue by ck37** [pablobarbera/twitter_ideology#1]
I was just curious - now that the article has been published, are there plans to publish the additional code and tutorial as referenced in the Readme.md?

**Comment by pablobarbera** [comment]
Yes! Thanks for the interest, and apologies for the delay. It's almost ready, and I hope to release everything in the next couple of weeks (dissertation comes first... :-) )

**Comment by ck37** [comment]
Excellent, sounds great!

**Comment by pablobarbera** [comment]
@ck37 So... it took a while, but I finally added all the additional code and tutorial that I promised a long time ago!

**Comment by ck37** [comment]
Looks awesome, thanks :)
