### ISSUE TITLE
oauth authentication fails in Windows 10

### ISSUE THREAD

**Issue by kbenoit** [pablobarbera/twitter_ideology#11]
This works fine in macOS, but on Windows 10, it fails. (R 3.6.1, everything up to date.)

```r
> load("V:/GitHub/lse-my472/lse-my472.github.io/week07/my_oauth.rda")
> library("ROAuth")
> library("tweetscores")
Loading required package: R2WinBUGS
Loading required package: coda
Loading required package: boot
Registered S3 method overwritten by 'dplyr':
  method           from
  print.rowwise_df     
##
## tweetscores: tools for the analysis of Twitter data
## Pablo Barbera (USC)
## www.tweetscores.com
##
> getUsers(screen_names="LSEnews", oauth = my_oauth)[[1]]$screen_name
Error in function (type, msg, asError = TRUE)  : 
  Unknown SSL protocol error in connection to api.twitter.com:443 
> packageVersion("tweetscores")
[1] ‘0.2.1’
```

**Comment by victore82** [comment]
Any news on this? I´m having the same problem. Thanks

**Comment by floeblenkamp** [comment]
I would also be interested if this has been resolved. Same issue for me.

**Comment by pallomamarciano** [comment]
> This works fine in macOS, but on Windows 10, it fails. (R 3.6.1, everything up to date.)
> 
> ```r
> > load("V:/GitHub/lse-my472/lse-my472.github.io/week07/my_oauth.rda")
> > library("ROAuth")
> > library("tweetscores")
> Loading required package: R2WinBUGS
> Loading required package: coda
> Loading required package: boot
> Registered S3 method overwritten by 'dplyr':
>   method           from
>   print.rowwise_df     
> ##
> ## tweetscores: tools for the analysis of Twitter data
> ## Pablo Barbera (USC)
> ## www.tweetscores.com
> ##
> > getUsers(screen_names="LSEnews", oauth = my_oauth)[[1]]$screen_name
> Error in function (type, msg, asError = TRUE)  : 
>   Unknown SSL protocol error in connection to api.twitter.com:443 
> > packageVersion("tweetscores")
> [1] ‘0.2.1’
> ```

Hi, guys. I did not find any solution for Windows. So, I've tried to install Ubuntu in my WSL (version 2, Win 10) and it worked. Now, I use the package on R for Ubuntu inside Windows

**Comment by pablobarbera** [comment]
Sorry it took me such a long time to get to this! Fixing was more complex than I thought and required refactoring the entire package to use a different authentication method. This is now fixed in the latest version of the package, although in general I would advice using rtweet, which (as implied by its availability on CRAN) will generally be better maintained in the future.
