### ISSUE TITLE
Unknown SSL protocol error 

### ISSUE THREAD

**Issue by pallomamarciano** [pablobarbera/twitter_ideology#12]
Hi, Pablo!

Thank you very much for your time in building the Tweetscores package.

I was following the steps from your Twitter Ideology workshop and I am facing a problem when trying to create the my_oauth file. 

1. _Unknown SSL protocol error in connection to api.twitter.com:443_ or 
2. _error setting certificate verify locations: CAfile: CApath: none_

I have spent a long time trying to figure out a way to conclude this step but I did no succeed (including all the tutorials in Stackoverflow, Youtube,... about certificates). I can use my credentials in twitteR and Rtweet just fine. Only trying the $handshake with Tweetscores the problems appear. 

I am very interested in this solution because I want to use the package in my dissertation about misinformation in Brazilian social media.

I hope this message can reach you.

Thank you,

Palloma

**Comment by Bernardo1998** [comment]
Same issue here! Any updates/solution would be greatly appreciated. Thank you!

**Comment by pallomamarciano** [comment]
> Same issue here! Any updates/solution would be greatly appreciated. Thank you!

Hi, Bernardo. I did not find any solution for my OS (Win 10). So, I've tried to install Ubuntu in my WSL virtual environment and it worked. Now, I use the package on R for Ubuntu

**Comment by Bernardo1998** [comment]
> > Same issue here! Any updates/solution would be greatly appreciated. Thank you!
> 
> Hi, Bernardo. I did not find any solution for my OS (Win 10). So, I've tried to install Ubuntu in my WSL virtual environment and it worked. Now, I use the package on R for Ubuntu

Hi Palloma. Thank you so much for the advise! Switching to Ubuntu solved this problem for me as well.

**Comment by pablobarbera** [comment]
Sorry it took me such a long time to get to this! Fixing was more complex than I thought and required refactoring the entire package to use a different authentication method. This is now fixed in the latest version of the package, although in general I would advice using rtweet, which (as implied by its availability on CRAN) will generally be better maintained in the future.
