### ISSUE TITLE
getFollowers() function indefinitely loops on error

### ISSUE THREAD

**Issue by VirginiaMass** [pablobarbera/twitter_ideology#14]
Hello Dr. Barberá,

My code has been running for three days now and I was able to get followers from only 96 accounts of the congress pool.
The job is continuously looping all the accounts in the pool but I keep receiving the "Error! On to the next one...", without any indication of what could be triggering the error.

I tried to set the "verbose" argument to TRUE and the only difference I noticed is that after ~20 error messages the red log "15 API calls left" appeared.

```
Error! On to the next one...SarahPalinUSA --- 1377973  followers ---  495  accounts left!
15 API calls left
5000 followers. Next cursor: 1694776736622473753
14 API calls left
Error! On to the next one...SenCapito --- 85403  followers ---  495  accounts left!
```

Do you have any idea why this might be happening and what this means?
Thank you in advance.

**Comment by pablobarbera** [comment]
Hi @VirginiaMass - could you share the full code you're using? I suspect that the error is triggered when the function is looping over your Twitter tokens, and perhaps there's one that doesn't have the proper authentication. Or this could also happen if you're calling a folder with multiple tokens, and one of them is not a proper token.
