### ISSUE TITLE
compatible with Twitter API v2?

### ISSUE THREAD

**Issue by amberxuqianchen** [pablobarbera/twitter_ideology#15]
I had Twitter API v1 Standard version and v2 Academic Premium version. Using v2 will show an error when getfriends.

**Comment by pablobarbera** [comment]
Hi @amberxuqianchen - I won't be able to support v2 of the API, but I believe there already exist alternatives on CRAN such as [academictwitteR](https://cran.r-project.org/web/packages/academictwitteR/index.html), so I would recommend you check out those options if you haven't already. Thank you!

**Comment by amberxuqianchen** [comment]
> Hi @amberxuqianchen - I won't be able to support v2 of the API, but I believe there already exist alternatives on CRAN such as [academictwitteR](https://cran.r-project.org/web/packages/academictwitteR/index.html), so I would recommend you check out those options if you haven't already. Thank you!

Thank you! I use twarc in python to get a list of friend ids and then use your Rpackage. Works well!
