### ISSUE TITLE
`estimateIdeology2()` documentation is misleading

### ISSUE THREAD

**Issue by johnhenrypezzuto** [pablobarbera/twitter_ideology#16]
The documentation for `estimateIdeology2()` reads:

> #' @return The function returns a matrix with summary statistics of the posterior
> #' distribution of the two estimated parameters, beta (political interest) and
> #' theta (ideology).

However, the function only returns the `theta` parameter. Either the documentation or the output of the function should be updated to match.

**Comment by pablobarbera** [comment]
Thank you! The documentation was indeed inaccurate. Now fixed.
