### ISSUE TITLE
oauth argument is unused and also missing

### ISSUE THREAD

**Issue by jmrphy** [pablobarbera/twitter_ideology#6]
Hi Pablo, I spent a couple hours trying many solutions, so with no luck I think there's probably an issue. I'm not a good enough programmer to be much help, I'm afraid, but here's the best I can give you.

Something seems screwy because `estimateIdeology('jmrphy', oauth = my_oauth)` will throw the error `Error in estimateIdeology("jmrphy", oauth = my_oauth) : unused argument (oauth = my_oauth)`

But `estimateIdeology('jmrphy')` will throw an error for `Error in getOAuth(oauth, verbose = verbose) : argument "oauth" is missing, with no default`

It seems very strange to see both of these errors at once, especially because `getFriends('jmrphy', oauth = my_oauth)` works!

I couldn't even find anything about any getOAuth function. I also noticed the documentation is a little unclear about the oauth methods, with getFriends advising to fill the oauth argument with a list of credentials including access tokens, whereas other parts of the documentation advise filling the oauth argument with the saved handshake information. I've tried just about all possible combinations and the usual suspects such as restarting R, updating packages, etc. But no luck. 

Thanks for anything you can say about this, it's an incredible package. :-)

**Comment by pablobarbera** [comment]
Hi @jmrphy - thanks for your kind words!

Can you try with the following? You will need to add your list of friends as an argument to `estimateIdeology`. If it's missing, in theory the function should have tried to get your friends in a single step, but I now see there's a bug in the code and it won't do it. I'll fix it when I have the time. But in the meantime I believe the following should work (or at least it did for me!)

```{r}
> friends <- getFriends("jmrphy", oauth="~/Dropbox/credentials/twitter/")
/Users/pablobarbera/Dropbox/credentials/twitter//oauth_token_18
15 API calls left
2782 friends. Next cursor: 0
14 API calls left
> estimateIdeology("jmrphy", friends)
Error in estimateIdeology("jmrphy", friends) : User follows 0 elites!
> estimateIdeology2("jmrphy", friends)
jmrphy follows 1 elites: Politics_PR
[1] -2.291648
```

**Comment by jmrphy** [comment]
Nice, yep that does the trick. Thanks! In case anyone else comes to this before you fix it, I'll share here a little loop that uses this workaround to build a dataframe of tweetscores for a vector of screen names.

 [twitterscores_collect.R](https://gist.github.com/jmrphy/7601e07020d67f70ed473e3ba10ae8af#file-twitterscores_collect-r)

**Comment by pablobarbera** [comment]
This is now fixed in the latest version of the package, so closing this now.
