### ISSUE TITLE
Locale Issue in formatTwDate 

### ISSUE THREAD

**Issue by msaeltzer** [pablobarbera/twitter_ideology#9]
Not a real issue but in non-US OS this does not work properly due to locale settings - drove me crazy because the abbreviations for months in the Time stamps depend on your windows settings 

fix:

formatTwDate <- function(datestring, format="datetime"){
Sys.setlocale("LC_TIME", "English") # change locale settings
    if (format=="datetime"){
        date <- as.POSIXct(datestring, format="%a %b %d %H:%M:%S %z %Y")
    }
    if (format=="date"){
        date <- as.Date(datestring, format="%a %b %d %H:%M:%S %z %Y")
    }
Sys.setlocale('LC_TIME',Sys.getlocale('LC_COLLATE')) # return to normal
return(date)
}

best regards Marius

**Comment by pablobarbera** [comment]
Thanks @msaeltzer ! Great idea. Just fixed it.
